name: Sync Fork

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - name: Check fork
        if: github.repository_owner != 'Stoppedwumm'
        run: exit 0
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: Stoppedwumm
          base: master
          head: master
          ignore_fail: true
          auto_merge: true
